// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWHEv0QKf6c37sGHL3zVQMWvCgBZoS8g',
    appId: '1:609500133322:web:00cfbcab04e3611bed4133',
    messagingSenderId: '609500133322',
    projectId: 'tilefetch',
    authDomain: 'tilefetch.firebaseapp.com',
    storageBucket: 'tilefetch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8XFt3zO8cyhMeesFYuUDS4728cktXSvI',
    appId: '1:609500133322:android:4dfb5ce4ae596dafed4133',
    messagingSenderId: '609500133322',
    projectId: 'tilefetch',
    storageBucket: 'tilefetch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6gkQ9gIdFQDQ9FnZePl-InKB3jP3zJZY',
    appId: '1:609500133322:ios:ed05ae7cd8d721caed4133',
    messagingSenderId: '609500133322',
    projectId: 'tilefetch',
    storageBucket: 'tilefetch.firebasestorage.app',
    iosBundleId: 'com.example.tilefetch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6gkQ9gIdFQDQ9FnZePl-InKB3jP3zJZY',
    appId: '1:609500133322:ios:ed05ae7cd8d721caed4133',
    messagingSenderId: '609500133322',
    projectId: 'tilefetch',
    storageBucket: 'tilefetch.firebasestorage.app',
    iosBundleId: 'com.example.tilefetch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWHEv0QKf6c37sGHL3zVQMWvCgBZoS8g',
    appId: '1:609500133322:web:249fa9e7a53e536fed4133',
    messagingSenderId: '609500133322',
    projectId: 'tilefetch',
    authDomain: 'tilefetch.firebaseapp.com',
    storageBucket: 'tilefetch.firebasestorage.app',
  );
}
